module.exports = {
    NO_API_ACCESS:'You have no access for this API',
    NO_COUNT_OF_BOOKS:'Insufficient number of books. Order was rejected! Missing books:',
    ORDER_ALREADY_COMPLETED:'This order already completed. Rejected!',
    SIGN_UP_SUCCESS:'Successfully registered!',
    SIGN_IN_SUCCESS:'Successfully logged In!',
    USER_UPDATE_SUCCESS:'User successfully updated!',
    USER_DELETE_SUCCESS:'User successfully deleted!',
    BOOK_ADD_SUCCESS:'Book successfully added!',
    BOOK_UPDATE_SUCCESS:'Book successfully updated!',
    BOOK_DELETE_SUCCESS:'Book successfully deleted!',
    ORDER_CREATE_SUCCESS:'Order successfully created! Waiting for confirm ...',
    ORDER_CONFIRM_SUCCESS:'Order successfully confirmed! Waiting for phone call for details ...',
    ORDER_DELETE_SUCCESS:'Order successfully deleted!',
    ORDER_REJECTED:'Order successfully rejected!',
};